version: 2

models:
  - name: stg_users
    columns:
      - name: user_id
        tests: [not_null, unique]

  - name: stg_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: user_id
        tests: [not_null]

  - name: stg_order_items
    columns:
      - name: order_item_id
        tests: [not_null, unique]
      - name: order_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]

  - name: stg_products
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: stg_inventory_items
    columns:
      - name: inventory_item_id
        tests: [not_null, unique]

  - name: stg_events
    columns:
      - name: events_id
        tests: [not_null, unique]
      - name: event_type
        tests:
          - accepted_values:
              values: ['home','product','department','cart','purchase','cancel']

  - name: stg_distribution_centers
    columns:
      - name: distribution_id
        tests: [not_null, unique]
